### ISSUE TITLE
Unable to use with KOPS prior to 1.8

### ISSUE THREAD

**Issue by azman0101** [liggitt/audit2rbac#15]
Since an `--audit-policy-file` parameter must be defined to make audit2rbac works. Cluster built with KOPS < 1.8 can't use the tool to generates RBAC role and binding objects.

"Audit Policy File" had been merged only for KOPS 1.8:
https://github.com/kubernetes/kops/pull/3692

Or, is this ok to use KOPS 1.8 with Kubernetes 1.6 ?

**Comment by igoratencompass** [comment]
If this helps, I have used 1.8 to manage and upgrade my 1.6 cluster to 1.7 and then 1.7 to 1.8. I think kops maintains backword compatibility so you can manage all k8s versions using the latest kops version.

**Comment by liggitt** [comment]
The audit policy file option is available in K8s 1.8. I believe that only kops 1.8 and up can be used to deploy a 1.8 server, but you would need to verify that with the kops documentation.
