### ISSUE TITLE
audit2rbac as a kubectl plugin

### ISSUE THREAD

**Issue by petermbenjamin** [liggitt/audit2rbac#19]
Thank you @liggitt for this extremely useful tool.

Are you open to making this tool available and usable as a kubectl plugin?

If so, I would not mind working on PR for this.

**Comment by liggitt** [comment]
Can you describe how you would expect it to behave differently as a kubectl plugin?

**Comment by petermbenjamin** [comment]
As a plugin, the user experience would be consistent (e.g. `kubectl audit2rbac ...`)
As a [`krew`](https://github.com/kubernetes-sigs/krew)-supported plugin, `audit2rbac` would become much more easily discoverable (e.g. `kubectl krew search` would return `audit2rbac` as one of the results) and upgradeable (e.g. `kubectl krew upgrade audit2rbac`)

**Comment by liggitt** [comment]
> As a plugin, the user experience would be consistent (e.g. kubectl audit2rbac ...)

I don't really see how nesting the command underneath `kubectl` improves the user experience of a standalone log processing tool. Are you envisioning other functional changes?

> As a krew-supported plugin, audit2rbac would become much more easily discoverable

Beyond making a zip containing the binary renamed to kubectl-audit2rbac, what changes would be required?

**Comment by petermbenjamin** [comment]
>Are you envisioning other functional changes?
No other functional changes envisioned.

>what changes would be required?
A yaml manifest file that points to the download URL and describes a few other details, checked in to [krew index](https://github.com/kubernetes-sigs/krew-index) repo.

This request is primarily to enable easy discoverability and seamless upgradability, with the added bonus of plugin experience consistency, not just being nested as a subcommand under `kubectl`, but gaining the rest of the benefits of being part of the `kubectl` plugin ecosystem (e.g. `kubectl krew <list|remove|install|upgrade|search>`).

Lastly, I want to clarify that this would not change the fact that `audit2rbac` can continue to be used as a standalone tool, if users so choose. They would simply download the tool from this repo and `mv kubectl-audit2rbac /some/path/audit2rbac`.

**Comment by liggitt** [comment]
> Lastly, I want to clarify that this would not change the fact that audit2rbac can continue to be used as a standalone tool, if users so choose. They would simply download the tool from this repo and mv kubectl-audit2rbac /some/path/audit2rbac.

I see this primarily as a stand-alone tool. Making it a kubectl plugin only for purposes of distribution seems odd to me. I would not necessarily object to a special zip containing a renamed `kubectl-audit2rbac` binary, but I would expect the primary build artifacts to continue to produce `audit2rbac` binaries
