### ISSUE TITLE
Documentation error ?

### ISSUE THREAD

**Issue by byte13** [liggitt/audit2rbac#21]
Hi Jordan,

First, thank's for the tool.
I'm crrently testing it and failed, first, activating auditing on a cluster initiated using kubeadm.

Apparently the proper option is : 
--feature-gates=AdvancedAudit**ing**=true
instead of 
--feature-gates=AdvancedAudit=true

Your documentation mention the later.

This other issue helped me pointing out the problem : 
https://github.com/kubernetes/kubernetes/commit/3920b0ec648b1bf2eedf02739f0f174e6b41770e

Thank's again and best regards !
Thierry

**Comment by liggitt** [comment]
thanks for the report, I went ahead and removed that bit from this repo's docs and just linked to the k8s docs, since the feature's been enabled by default since 1.8
